### ISSUE TITLE
Impulse Responses across regimes

### ISSUE THREAD

**Issue by RightHandOfDoom** [bsvars/bsvars#53]
Hello! 
Sorry to bother with another question:

here is my workflow:
df%>%specify_bsvar_msh$new(p=6,B=B,M=2)%>%      
  estimate(S = 100) %>%               
  estimate(S = 5000) -> out_ms

I am interested in comparing impulse responses across both regimes.
If I am not mistaken, an earlier version of the package allowed for this option, but I am not sure

Do you know any way how this could be achieved? 
Thank you very much again for your help !!

**Comment by donotdespair** [comment]
Hey,

This model has only the conditional variances of the structural shocks that are changing with the Markov process, therefore, the name of the model: Markov-Switching Heteroskedasticity. The autoregressive parameters and the contemporaneous effects are constant over time in this package for all models. Therefore, the IRFs will have the same shape for all heteroskedastic models.

Now, what changes over time, with the Markov states, are the conditional variances of the structural shocks. Some people like to plot IRFs to *a shock of magnitude equal to one standard deviation*. The variances change over time, so do standard deviations, and so would the IRFs. But this is just a matter of rescaling all the IRFs in the regimes by a constant that is equal to the average standard deviation over for a regime. So, little new info is introduced here. If you want to implement this, you need to code by yourself and the *SVAR Tools* chapter of Lütkepohl & Kilian textbook on SVARs should provide all the info on how to...

I have another package **bsvarTVPs** that allows for Markov switching in contemporaneous effects. It's available on GH. But we will not provide any helpfiles or documentation there until the underlying paper is on the way to be published in a journal. Sorry!

Let me know if this helps :)

Cheers, T

**Comment by RightHandOfDoom** [comment]
No problem! Thank you very much again for the helpful explanation!
I probably mixed this functionality up with another package.

The bsvarTVPs package looks promising. I tried to install it but there were compilation issues for some reason. I'll look into it & post maybe a question there.

Thanks again!
