### ISSUE TITLE
Please correct before 2024-07-04

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvars#82]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_bsvars.html>.

Please correct before 2024-07-04 to safely retain your package on CRAN.

Do remember to look at the 'Additional issues'.

The CRAN Team

**Comment by conradsnicta** [comment]
@donotdespair Related issue affecting bsvars: https://github.com/RcppCore/RcppArmadillo/issues/443

**Comment by donotdespair** [comment]
Hey, thanks so much @conradsnicta I know of that issue, and I was in touch with Dirk regarding the required steps. I know what to do and I am sitting to this right now! 

BTW, I'm a huge fan of **Armadillo** and **RcppArmadillo** and I will use this opportunity to thank you for your contributions in this field!

Greetings, Tomasz

**Comment by donotdespair** [comment]
- [ ] have a look at the code for `verify_autoregressive_heterosk_cpp` and `verify_autoregressive_homosk_cpp` if it does what it should
