### ISSUE TITLE
Decomposition Plots Do not Have Legend

### ISSUE THREAD

**Issue by ccoleman9** [bsvars/bsvars#85]
Currently the decomp plots do not have legends and there does not seem to be an easy way to add them. Slight suggestion to build plots as ggplot objects to make them user-friendly.

**Comment by donotdespair** [comment]
Hey @ccoleman9 That was quick! Thanks a lot!

My plan is to make it a part of [version 3.1](https://github.com/bsvars/bsvars/milestone/6) that I plan to send to CRAN within a month.

Greetings, Tomasz

**Comment by donotdespair** [comment]
Hey @ccoleman9 

Just a small update that in this issue, I am working on the legend for the historical decomposition plots.

I am not including **ggplot2** in this package for several reasons. One is that I am a base-package person 😸  But more importantly, **ggplot2** inctroduces too many dependencies, which I would like to avoid by all means. Too many dependencies increase the risk for the maintainer of receiving an email that some other package changes and then one has two weeks for implementing the update or the package is taken down from CRAN. 

I am thinnking of maybe developing a package for ggplots and tidymodels for **bsvars**, but I am not planning this ATM.

Greetings, Tomasz

**Comment by donotdespair** [comment]
- [ ] develop legend for `plot.PosteriorFEVD`
- [ ] develop legend for `plot.PosteriorHD`
