### ISSUE TITLE
Conditional forecast with exogenous variables

### ISSUE THREAD

**Issue by DawievLill** [bsvars/bsvars#96]
Good day, 

First of all, thank you for the great package. 

At this moment I can easily get conditional forecasts using the examples from the CRAN documentation. However, I am struggling to get the conditional forecasts with exogenous variables to work. In particular, I want to be able to specify a value over the forecasting horizon for an exogenous variable. Could you possibly provide an example of how this would work within the `bsvars` package. 

Thank you!

**Comment by donotdespair** [comment]
Hey Dear @DawievLill 

How are you? Thanks for your question! I sincerely apologise for my late reply! 

Here's a short script for forecasting using a model with exogenous variables:
```

# set forecasting horizon
H = 8

# upload data
data(us_fiscal_lsuw)
data(us_fiscal_ex)

us_fiscal_ex_fore = cbind(153:(153 + H - 1), (153:(153 + H - 1))^2, rep(0, H))

  # specify the model and set seed
set.seed(123)
specification  = specify_bsvar$new(us_fiscal_lsuw, exogenous = us_fiscal_ex)

# run the burn-in
burn_in        = estimate(specification, 5)

# estimate the model
posterior      = estimate(burn_in, 10, thin = 2)

# sample from predictive density 2 years ahead
predictive     = forecast(
                  posterior, 
                  horizon = 8,
                  exogenous = us_fiscal_ex_fore
                )
```
The essential point is to create the future values of the exogenous variables. They must align with the forecast horizon in terms of the number of rows and the exogenous variables matrix in terms of the number of columns. Above, I create a matrix `us_fiscal_ex_fore` with apprpriate values. BTW, it might be usefulf for you to know that the first exogenous variable here is the demeaned trend, $t - \bar{t}$, the second is cuadratic trend $(t - \bar{t})^2$, and the third is just a dummy variable for one-period outlier.

Let me know if this works for you.

Greetings, T @donotdespair

**Comment by donotdespair** [comment]
BTW @DawievLill  

I let myself use this issue to improve the package documentation with that respect! Thanks so much for pointing out implicitly that this is not explained in the examples!

- [ ] expand examples to include forecasting for a model with exogenous variables
- [ ] provide matrices for forecasting example as data object `us_fiscal_ex_fore `
- [ ] do the same for conditional forecasts! that is:
  - [ ] expand examples
  - [ ] provide a sample matrix with `us_fiscal_cond_fore`
