### ISSUE TITLE
Optimal lag selection

### ISSUE THREAD

**Issue by magsarah** [bsvars/bsvars#99]
Hello, 

I have a question regarding the optimal number of lags for my Bayesian SVAR analysis, which uses monthly data. The literature often uses 12 or 24 lags, but when I applied the selection criteria (BIC and AIC), both suggested that only one lag is optimal.

Given this, should I follow the standard practice of using 12 lags, or stick to the one lag suggested by the selection criteria? Alternatively, is there another approach you would recommend in this situation?

Please find below the R code I use to select the number of lags:

var_data <- Dataset %>%
  select(Y1, Y2, Y3, Y4, Y5)

var_data <- na.omit(var_data)

var_ts <- ts(var_data, start = c(1999, 1), frequency = 12)

lag_selection <- VARselect(var_ts, lag.max = 30, type = "const")
print(lag_selection)

**Comment by donotdespair** [comment]
Hey @magsarah 

So you are interestined in determining the lag order using other models and then apply the choice to the bsvars package?

I want to understand before wrtie anything more. Thanks.

Cheers, Tomasz

**Comment by magsarah** [comment]
Dear Dr.  Tomasz,

Thanks much for your reply. Yes, that is correct. I want to use the
information criteria to define the number of lags, and then define this
when estimating the Bayesian SVAR model.
To define the optimal lag order, I used the R code I included in my post.

Looking forward to your guidance.

Best regards
Sarah

**Comment by donotdespair** [comment]
OK! 

Look, the lag order has to be selected for a particular model. Bayesian models with the hierarchical prior distribution will have different lags selected than plain VAR models from package **vars**.

Indeed, there are some uncontroversial choices like 12 or 13 for monthly data. But unless one uses a criterion suitable for the particular model estimated using specific data, we don't know for sure. 

The only existing possibility to verify the lag order supported by the data using the package **bsvars** would be to estimate a general model, say with 14 lags, and then use function `verify_autoregression()` to test whether:
- $A_{14} = 0$
- $A_{14} = A_{13} = 0$
- $A_{14} = A_{13} = A_{12} = 0$
- and so on.

Such a procedure computes the Bayes factor for the hypothesis using Savage-Dickey Density Ratio. This is a formally sound way to proceed.

Please let me know if this helps.

Cheers,

Tomasz
